version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2021!"
      MYSQL_DATABASE: "programandoFuturo"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge